export const TIPS = [
  { nipe: "clubs", value: "A", tips: ["Peito"] },
  { nipe: "clubs", value: "2", tips: ["Pino"] },
  { nipe: "clubs", value: "3", tips: ["Pomo"] },
  { nipe: "clubs", value: "4", tips: ["Porre"] },
  { nipe: "clubs", value: "5", tips: ["Pelé"] },
  { nipe: "clubs", value: "6", tips: ["Paxá"] },
  { nipe: "clubs", value: "7", tips: ["Paca"] },
  { nipe: "clubs", value: "8", tips: ["Pufe"] },
  { nipe: "clubs", value: "9", tips: ["Papai"] },
  { nipe: "clubs", value: "10", tips: ["Poço"] },
  { nipe: "clubs", value: "J", tips: ["Povo"] },
  { nipe: "clubs", value: "Q", tips: ["Poda"] },
  { nipe: "clubs", value: "K", tips: ["Pêra"] },

  { nipe: "hearts", value: "A", tips: ["Cutia"] },
  { nipe: "hearts", value: "2", tips: ["Cone"] },
  { nipe: "hearts", value: "3", tips: ["Cama"] },
  { nipe: "hearts", value: "4", tips: ["Carro"] },
  { nipe: "hearts", value: "5", tips: ["Cola"] },
  { nipe: "hearts", value: "6", tips: ["Coxa"] },
  { nipe: "hearts", value: "7", tips: ["Coca"] },
  { nipe: "hearts", value: "8", tips: ["Café"] },
  { nipe: "hearts", value: "9", tips: ["Copa"] },
  { nipe: "hearts", value: "10", tips: ["Casa"] },
  { nipe: "hearts", value: "J", tips: ["Cova"] },
  { nipe: "hearts", value: "Q", tips: ["Corda"] },
  { nipe: "hearts", value: "K", tips: ["Cara"] },

  { nipe: "spades", value: "A", tips: ["Tatu"] },
  { nipe: "spades", value: "2", tips: ["Tainha"] },
  { nipe: "spades", value: "3", tips: ["Time"] },
  { nipe: "spades", value: "4", tips: ["Torre"] },
  { nipe: "spades", value: "5", tips: ["Talo"] },
  { nipe: "spades", value: "6", tips: ["Tocha"] },
  { nipe: "spades", value: "7", tips: ["Touca"] },
  { nipe: "spades", value: "8", tips: ["Tufo"] },
  { nipe: "spades", value: "9", tips: ["Tábua"] },
  { nipe: "spades", value: "10", tips: ["Taz"] },
  { nipe: "spades", value: "J", tips: ["Tevê"] },
  { nipe: "spades", value: "Q", tips: ["Toda"] },
  { nipe: "spades", value: "K", tips: ["Touro"] },

  { nipe: "diamonds", value: "A", tips: ["Seta"] },
  { nipe: "diamonds", value: "2", tips: ["Sino"] },
  { nipe: "diamonds", value: "3", tips: ["Sumô"] },
  { nipe: "diamonds", value: "4", tips: ["Serra"] },
  { nipe: "diamonds", value: "5", tips: ["Selo"] },
  { nipe: "diamonds", value: "6", tips: ["Soja"] },
  { nipe: "diamonds", value: "7", tips: ["Saco"] },
  { nipe: "diamonds", value: "8", tips: ["Sofá"] },
  { nipe: "diamonds", value: "9", tips: ["Sopa"] },
  { nipe: "diamonds", value: "10", tips: ["Saci"] },
  { nipe: "diamonds", value: "J", tips: ["Seiva"] },
  { nipe: "diamonds", value: "Q", tips: ["Soda"] },
  { nipe: "diamonds", value: "K", tips: ["Siri"] },
];

